/**
 * Release-group patterns and streaming-platform aliases.
 * Names/codes adapted from MoviePilot v3 as prior art
 * (app/domain/meta/releasegroup.py, streamingplatform.py).
 * TypeScript data tables — not a copy of MoviePilot source.
 */

/** Alternation pieces for the lookbehind/lookahead group matcher. */
export const RELEASE_GROUP_PATTERNS: readonly string[] = [
  "FF(?:(?:A|WE)B|CD|E(?:DU|B)|TV)",
  "Audies",
  "AD(?:Audio|E(?:book|)|Music|Web)",
  "BeiTai",
  "Bts(?:CHOOL|HD|PAD|TV)",
  "Zone",
  "CarPT",
  "CHD(?:Bits|PAD|(?:|HK)TV|WEB|)",
  "StBOX",
  "OneHD",
  "Lee",
  "xiaopie",
  "(?:(?:iNT|(?:HALFC|Mini(?:S|H|FH)D))-|)TLF",
  "(?:DG|GBWE)B",
  "Hares(?:(?:M|T)V|Web|)",
  "HDA(?:pad|rea|TV)",
  "EPiC",
  "HDC(?:hina|TV|)",
  "k9611",
  "tudou",
  "iHD",
  "D(?:ream|BTV)",
  "(?:HD|QHstudI)o",
  "beAst(?:TV|)",
  "HDH(?:ome|Pad|TV|WEB|)",
  "HDPT(?:Web|)",
  "HDS(?:ky|TV|Pad|WEB|)",
  "AQLJ",
  "HDZ(?:one|)",
  "HHWEB",
  "HTPT",
  "FRDS",
  "Yumi",
  "cXcY",
  "L(?:eague(?:(?:C|H)D|(?:M|T)V|NF|WEB)|HD)",
  "i18n",
  "CiNT",
  "MTeam(?:TV|)",
  "MPAD",
  "MWeb",
  "Our(?:Bits|TV)",
  "FLTTH",
  "Ao",
  "PbK",
  "MGs",
  "iLove(?:HD|TV)",
  "Panda",
  "AilMWeb",
  "PiGo(?:NF|(?:H|WE)B)",
  "PTer(?:DIY|Game|(?:M|T)V|WEB|)",
  "PTH(?:Audio|eBook|music|ome|tv|WEB|)",
  "PTsbao",
  "OPS",
  "F(?:Fans(?:AIeNcE|BD|D(?:VD|IY)|TV|WEB)|HDMv)",
  "SGXT",
  "PuTao",
  "CMCT(?:V|)",
  "Shark(?:WEB|DIY|TV|MV|)",
  "TJUPT",
  "TTG",
  "WiKi",
  "NGB",
  "DoA",
  "(?:ARi|ExRE)N",
  "B(?:MDru|eyondHD|TN)",
  "C(?:fandora|trlhd|MRG)",
  "DON",
  "EVO",
  "FLUX",
  "HONE(?:yG|)",
  "N(?:oGroup|T(?:b|G))",
  "PandaMoon",
  "SMURF",
  "T(?:EPES|aengoo|rollHD )",
  "ANi",
  "HYSUB",
  "KTXP",
  "LoliHouse",
  "MCE",
  "Nekomoe kissaten",
  "SweetSub",
  "MingY",
  "(?:Lilith|NC|AI)-Raws",
  "织梦字幕组",
  "枫叶字幕组",
  "猎户手抄部",
  "喵萌奶茶屋",
  "漫猫字幕社",
  "霜庭云花Sub",
  "北宇治字幕组",
  "氢气烤肉架",
  "云歌字幕组",
  "萌樱字幕组",
  "极影字幕社",
  "悠哈璃羽字幕社",
  "❀拨雪寻春❀",
  "沸羊羊(?:制作|字幕组)",
  "(?:桜|樱)都字幕组",
  "FROG(?:E|Web|)",
  "UB(?:its|WEB|TV)",
  "GM-Team",
  "AnimeS",
];

export interface StreamingPlatformSpec {
  /** Canonical `webSource` value. */
  name: string;
  /** Latin codes/names — only count next to WEB/WEB-DL/官源. */
  latin: readonly string[];
  /** CJK names — match without WEB. */
  cjk?: readonly string[];
}

export const STREAMING_PLATFORMS: readonly StreamingPlatformSpec[] = [
  { name: "HBO GO", latin: ["HBOGO", "HBO GO"] },
  { name: "Max", latin: ["HMAX", "Max"] },
  { name: "Disney+ MENA", latin: ["APPS", "Disney+ MENA"] },
  { name: "Disney+", latin: ["DSNP", "Disney+"], cjk: ["迪士尼+"] },
  { name: "Paramount+", latin: ["PMTP", "Paramount+"] },
  { name: "Paramount Network", latin: ["PMNT", "Paramount Network"] },
  { name: "PBS KIDS", latin: ["PBSK", "PBS KIDS"] },
  { name: "Discovery+", latin: ["DSCP", "Discovery+"] },
  { name: "Apple TV+", latin: ["ATVP", "Apple TV+"] },
  { name: "BBC iPlayer", latin: ["iP", "BBC iPlayer"] },
  { name: "CATCHPLAY+", latin: ["CATCHPLAY", "CATCHPLAY+", "CPP", "CTHP"] },
  { name: "DailyWire+", latin: ["DW", "DailyWire+", "DLWP"] },
  { name: "iQIYI", latin: ["iQIYI", "IQ"], cjk: ["爱奇艺"] },
  { name: "Netflix", latin: ["NF", "Netflix"], cjk: ["网飞", "奈飞"] },
  { name: "Amazon", latin: ["AMZN", "Amazon"], cjk: ["亚马逊"] },
  { name: "Hulu", latin: ["Hulu", "HULU", "Hulu Networks", "HuluJP"] },
  { name: "Peacock", latin: ["PCOK", "Peacock"] },
  { name: "Crunchyroll", latin: ["CR", "Crunchyroll"] },
  { name: "Bilibili", latin: ["Bilibili", "BG", "B-Global"], cjk: ["哔哩哔哩", "哔哩"] },
  { name: "WeTV", latin: ["WeTV"], cjk: ["腾讯视频", "腾讯"] },
  { name: "Youku", latin: ["Youku"], cjk: ["优酷"] },
  { name: "Mango", latin: ["Mango"], cjk: ["芒果"] },
  { name: "iTunes", latin: ["iT", "iTunes"] },
  { name: "Hotstar", latin: ["HS", "Hotstar"] },
  { name: "Movies Anywhere", latin: ["MA", "Movies Anywhere"] },
  { name: "Bravia Core", latin: ["BCORE", "Bravia Core"] },
  { name: "Microsoft Store", latin: ["MS", "Microsoft Store"] },
  { name: "Showtime", latin: ["SHO", "Showtime"] },
  { name: "Stan", latin: ["STAN", "Stan"] },
  { name: "SkyShowtime", latin: ["SKST", "SkyShowtime"] },
  { name: "Now", latin: ["NOW", "Now"] },
  { name: "Foxtel Now", latin: ["FXTL", "Foxtel Now"] },
  { name: "Binge", latin: ["BNGE", "Binge"] },
  { name: "Crackle", latin: ["CRKL", "Crackle"] },
  { name: "Rakuten TV", latin: ["RKTN", "Rakuten TV"] },
  { name: "Channel 4", latin: ["ALL4", "Channel 4"] },
  { name: "Adult Swim", latin: ["AS", "Adult Swim"] },
  { name: "Brtb TV", latin: ["BRTB", "Brtb TV"] },
  { name: "Canal+", latin: ["CNLP", "Canal+"] },
  { name: "Criterion Channel", latin: ["CRIT", "Criterion Channel"] },
  { name: "Food Network", latin: ["FOOD", "Food Network"] },
  { name: "Mubi", latin: ["MUBI", "Mubi"] },
  { name: "Google Play", latin: ["PLAY", "Google Play"] },
  { name: "YouTube", latin: ["YT", "YouTube"], cjk: ["油管"] },
  { name: "friDay", latin: ["friDay"] },
  { name: "KKTV", latin: ["KKTV"] },
  { name: "ofiii", latin: ["ofiii"] },
  { name: "LiTV", latin: ["LiTV"] },
  { name: "MyVideo", latin: ["MyVideo"] },
  { name: "Hami Video", latin: ["Hami", "Hami Video", "HamiVideo"] },
  { name: "meWATCH", latin: ["MW", "meWATCH"] },
  { name: "LINE TV", latin: ["LINETV", "LINE TV"] },
  { name: "Viu", latin: ["VIU", "Viu"] },
  { name: "Abema", latin: ["ABMA", "Abema", "AbemaTV"] },
  { name: "ADN", latin: ["ADN"] },
  { name: "AT-X", latin: ["AT-X"] },
  { name: "Baha", latin: ["Baha"] },
  { name: "DMM", latin: ["DMM"] },
  { name: "FOD", latin: ["FOD"] },
  { name: "Funimation", latin: ["FUNi", "Funimation"] },
  { name: "HIDIVE", latin: ["HIDI", "HIDIVE"] },
  { name: "U-NEXT", latin: ["UNXT", "U-NEXT"] },
  { name: "Filmarchiv Austria", latin: ["FAA", "Filmarchiv Austria"] },
  { name: "Comedy Central", latin: ["CC", "Comedy Central"] },
  { name: "9Now", latin: ["9NOW", "9Now"] },
  { name: "ABC", latin: ["ABC"] },
  { name: "AMC", latin: ["AMC"] },
  { name: "ZEE5", latin: ["ZEE5"] },
  { name: "WAVO", latin: ["WAVO"] },
  { name: "Shahid", latin: ["SHAHID", "Shahid"] },
  { name: "FlixOlé", latin: ["Flixole", "FlixOlé"] },
  { name: "Ici TOU.TV", latin: ["TOU", "Ici TOU.TV"] },
  { name: "Roku", latin: ["ROKU", "Roku"] },
  { name: "Kanopy", latin: ["KNPY", "Kanopy"] },
  { name: "Sun NXT", latin: ["SNXT", "Sun NXT"] },
  { name: "Curiosity Stream", latin: ["CUR", "Curiosity Stream"] },
  { name: "Channel 5", latin: ["MY5", "Channel 5"] },
  { name: "aha", latin: ["AHA", "aha"] },
  { name: "WOW Presents Plus", latin: ["WOWP", "WOW Presents Plus"] },
  { name: "JioCinema", latin: ["JC", "JioCinema"] },
  { name: "Dekkoo", latin: ["Dekkoo"] },
  { name: "Filmzie", latin: ["FILMZIE", "Filmzie"] },
  { name: "Hoichoi", latin: ["HoiChoi", "Hoichoi"] },
  { name: "Rakuten Viki", latin: ["VIKI", "Rakuten Viki"] },
  { name: "SF Anytime", latin: ["SF", "SF Anytime"] },
  { name: "Plex", latin: ["PLEX", "Plex"] },
  { name: "Shudder", latin: ["SHDR", "Shudder"] },
  { name: "Crave", latin: ["CRAV", "Crave"] },
  { name: "Cineplex Entertainment", latin: ["CPE", "Cineplex Entertainment"] },
  { name: "JF HC", latin: ["JF HC"] },
  { name: "JF", latin: ["JF"] },
  { name: "JFFP", latin: ["JFFP"] },
  { name: "Viaplay", latin: ["VIAP", "Viaplay"] },
  { name: "TubiTV", latin: ["TUBI", "TubiTV"] },
  { name: "PBS", latin: ["PBS"] },
  { name: "Lionsgate Play", latin: ["LGP", "Lionsgate Play"] },
  { name: "CTV", latin: ["CTV"] },
  { name: "Cineverse", latin: ["Cineverse"] },
  { name: "Love Nature", latin: ["LN", "Love Nature"] },
  { name: "Movistar Plus+", latin: ["MP", "Movistar Plus+"] },
  { name: "Runtime", latin: ["RUNTIME", "Runtime"] },
  { name: "STARZ", latin: ["STZ", "STARZ"] },
  { name: "fuboTV", latin: ["FUBO", "fuboTV"] },
  { name: "Tënk", latin: ["TENK", "Tënk"] },
  { name: "Knowledge Network", latin: ["KNOW", "Knowledge Network"] },
  { name: "tvo", latin: ["TVO", "tvo"] },
  { name: "OVID", latin: ["OVID"] },
  { name: "CBC Gem", latin: ["CBC", "CBC Gem"] },
  { name: "fandor", latin: ["FANDOR", "fandor"] },
  { name: "The CW", latin: ["CW", "The CW"] },
  { name: "Freeform", latin: ["FREE", "Freeform"] },
  { name: "A&E", latin: ["AE", "A&E"] },
  { name: "Lifetime", latin: ["LIFE", "Lifetime"] },
  { name: "WWE Network", latin: ["WWEN", "WWE Network"] },
  { name: "Cinemax", latin: ["CMAX", "Cinemax"] },
  { name: "Hallmark", latin: ["HLMK", "Hallmark"] },
  { name: "BYUtv", latin: ["BYU", "BYUtv"] },
  { name: "ViX", latin: ["ViX"] },
  { name: "Viceland", latin: ["VICE", "Viceland"] },
  { name: "TVING", latin: ["TVING"] },
  { name: "USA Network", latin: ["USAN", "USA Network"] },
  { name: "FOX", latin: ["FOX"] },
  { name: "TCM", latin: ["TCM"] },
  { name: "BravoTV", latin: ["BRAV", "BravoTV"] },
  { name: "TNT", latin: ["TNT"] },
  { name: "ZDF", latin: ["ZDF"] },
  { name: "IndieFlix", latin: ["IndieFlix"] },
  { name: "TLC", latin: ["TLC"] },
  { name: "HGTV", latin: ["HGTV"] },
  { name: "Animal Planet", latin: ["ANPL", "Animal Planet"] },
  { name: "Travel Channel", latin: ["TRVL", "Travel Channel"] },
  { name: "VH1", latin: ["VH1"] },
  { name: "Saina Play", latin: ["SAINA", "Saina Play", "SP"] },
  { name: "Oxygen", latin: ["OXGN", "Oxygen"] },
  { name: "PlayStation Network", latin: ["PSN", "PlayStation Network"] },
  { name: "Fawesome", latin: ["FAWESOME", "Fawesome"] },
  { name: "Klassiki", latin: ["KLASSIKI", "Klassiki"] },
  { name: "Star+", latin: ["STRP", "Star+"] },
  { name: "National Geographic", latin: ["NATG", "National Geographic"] },
  { name: "Reveel", latin: ["REVEEL", "Reveel"] },
  { name: "FYI Network", latin: ["FYI", "FYI Network"] },
  { name: "WATCH IT", latin: ["WatchiT", "WATCH IT"] },
  { name: "ITV", latin: ["ITVX", "ITV"] },
  { name: "Gaia", latin: ["GAIA", "Gaia"] },
  { name: "FlixLatino", latin: ["FlixLatino"] },
  { name: "CNN+", latin: ["CNNP", "CNN+"] },
  { name: "Troma", latin: ["TROMA", "Troma"] },
  { name: "Ivi", latin: ["IVI", "Ivi"] },
  { name: "Atresplayer", latin: ["A3P", "Atresplayer"] },
  { name: "7plus", latin: ["7PLUS", "7plus"] },
  { name: "SBS", latin: ["SBS"] },
  { name: "10Play", latin: ["TEN", "10Play"] },
  { name: "AUBC", latin: ["AUBC"] },
  { name: "Disney Networks", latin: ["DSNY", "Disney Networks"] },
  { name: "OSN+", latin: ["OSN", "OSN+"] },
  { name: "Sveriges Television", latin: ["SVT", "Sveriges Television"] },
  { name: "LaCinetek", latin: ["LACINETEK", "LaCinetek"] },
  { name: "Maxdome", latin: ["Maxdome"] },
  { name: "RTL+", latin: ["RTL", "RTL+"] },
  { name: "Arte", latin: ["ARTE", "Arte"] },
  { name: "Joyn", latin: ["JOYN", "Joyn"] },
  { name: "TV 2", latin: ["TV2", "TV 2"] },
  { name: "3sat", latin: ["3SAT", "3sat"] },
  { name: "filmingo", latin: ["FILMINGO", "filmingo"] },
  { name: "WOW", latin: ["WOW"] },
  { name: "Okko", latin: ["OKKO", "Okko"] },
  { name: "Go3", latin: ["Go3"] },
  { name: "Argo", latin: ["ARGP", "Argo"] },
  { name: "Voyo", latin: ["VOYO", "Voyo"] },
  { name: "vivamax", latin: ["VMAX", "vivamax"] },
  { name: "Filmin", latin: ["FILMIN", "Filmin"] },
  { name: "Mitele", latin: ["Mitele"] },
  { name: "ARD", latin: ["ARD"] },
  { name: "Bentkey", latin: ["BK", "Bentkey"] },
  { name: "Boomerang", latin: ["BOOM", "Boomerang"] },
  { name: "CBS", latin: ["CBS"] },
  { name: "Club illico", latin: ["CLBI", "Club illico"] },
  { name: "C More", latin: ["CMOR", "C More"] },
  { name: "CMT", latin: ["CMT"] },
  { name: "CNBC", latin: ["CNBC"] },
  { name: "Cooking Channel", latin: ["COOK", "Cooking Channel"] },
  { name: "CW Seed", latin: ["CWS", "CW Seed"] },
  { name: "DC Universe", latin: ["DCU", "DC Universe"] },
  { name: "Digiturk Dilediğin Yerde", latin: ["DDY", "Digiturk Dilediğin Yerde"] },
  { name: "Destination America", latin: ["DEST", "Destination America"] },
  { name: "Discovery Channel", latin: ["DISC", "Discovery Channel"] },
  { name: "dplay", latin: ["DPLY", "dplay"] },
  { name: "Dropout", latin: ["DRPO", "Dropout"] },
  { name: "EPIX MGM+", latin: ["EPIX", "EPIX MGM+"] },
  { name: "Esquire", latin: ["ESQ", "Esquire"] },
  { name: "E!", latin: ["ETV", "E!"] },
  { name: "Facebook Watch", latin: ["FBWatch", "Facebook Watch"] },
  { name: "FPT Play", latin: ["FPT", "FPT Play", "FPTP"] },
  { name: "France.tv", latin: ["FTV", "France.tv"] },
  { name: "GloboSat Play", latin: ["GLOB", "GloboSat Play"] },
  { name: "Globoplay", latin: ["GLBO", "Globoplay"] },
  { name: "go90", latin: ["GO90", "go90"] },
  { name: "History Channel", latin: ["HIST", "History Channel"] },
  { name: "Hungama Play", latin: ["HPLAY", "Hungama Play"] },
  { name: "Kaleidescape", latin: ["KS", "Kaleidescape"] },
  { name: "MBC", latin: ["MBC"] },
  { name: "ManoramaMAX", latin: ["MMAX", "ManoramaMAX"] },
  { name: "MSNBC", latin: ["MNBC", "MSNBC"] },
  { name: "Motor Trend OnDemand", latin: ["MTOD", "Motor Trend OnDemand"] },
  { name: "NBC", latin: ["NBC"] },
  { name: "Nebula", latin: ["NBLA", "Nebula"] },
  { name: "Nickelodeon", latin: ["NICK", "Nickelodeon"] },
  { name: "OnDemandKorea", latin: ["ODK", "OnDemandKorea"] },
  { name: "PokerGO", latin: ["POGO", "PokerGO"] },
  { name: "puhutv", latin: ["PUHU", "puhutv"] },
  { name: "Quibi", latin: ["QIBI", "Quibi"] },
  { name: "RTÉ", latin: ["RTE", "RTÉ"] },
  { name: "Seeso", latin: ["SESO", "Seeso"] },
  { name: "Spike", latin: ["SPIK", "Spike"] },
  { name: "Simply South", latin: ["SS", "Simply South"] },
  { name: "SyFy", latin: ["SYFY", "SyFy"] },
  { name: "TIMvision", latin: ["TIMV", "TIMvision"] },
  { name: "Tentkotta", latin: ["TK", "Tentkotta"] },
  { name: "TV4", latin: ["TV4"] },
  { name: "TV Land", latin: ["TVL", "TV Land"] },
  { name: "TVNZ", latin: ["TVNZ"] },
  { name: "UKTV", latin: ["UKTV"] },
  { name: "Discovery Velocity", latin: ["VLCT", "Discovery Velocity"] },
  { name: "Vimeo", latin: ["VMEO", "Vimeo"] },
  { name: "VRV Defunct", latin: ["VRV", "VRV Defunct"] },
  { name: "Watcha", latin: ["WTCH", "Watcha"] },
  { name: "NowPlayer", latin: ["NowPlayer"] },
  { name: "GagaOOLala", latin: ["Gaga", "GagaOOLala"] },
  { name: "MyTVSuper", latin: ["MyTVS", "MyTVSuper"] },
  { name: "BBC", latin: ["BBC"] },
  { name: "Now E", latin: ["NowE", "Now E"] },
  { name: "Wavve", latin: ["WAVVE", "Wavve"] },
  { name: "SE", latin: ["SE"] },
  { name: "BritBox", latin: ["BritBox"] },
  { name: "Anime on Demand", latin: ["AOD", "Anime on Demand"] },
  { name: "AF", latin: ["AF"] },
  { name: "Bandai Channel", latin: ["BCH", "Bandai Channel"] },
  { name: "VideoMarket", latin: ["VMJ", "VideoMarket"] },
  { name: "Laftel", latin: ["LFTL", "Laftel", "LFTLNET"] },
  { name: "Wakanim", latin: ["WAKA", "Wakanim", "WAKANIM"] },
  { name: "AnimeOnegai", latin: ["AO", "AnimeOnegai"] },
  { name: "Lemino", latin: ["Lemino"] },
  { name: "Vidio", latin: ["VIDIO", "Vidio"] },
  { name: "TVer", latin: ["TVER", "TVer"] },
  { name: "MBS", latin: ["MBS"] },
  { name: "Jonu Play", latin: ["JONU", "Jonu Play"] },
  { name: "Pluto TV", latin: ["PlutoTV", "Pluto TV"] },
  { name: "dTV", latin: ["dTV"] },
  { name: "Nymey", latin: ["NYMEY", "Nymey"] },
  { name: "SAMANSA", latin: ["SMNS", "SAMANSA"] },
  { name: "HBO", latin: ["HBO"] },
  { name: "LOCIPO", latin: ["LOCIPO"] },
  { name: "DANET", latin: ["DANT", "DANET"] },
  { name: "OceanVeil", latin: ["OV", "OceanVeil"] },
];

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function latinTokenPattern(token: string): string {
  const body = token
    .split(/\s+/)
    .map((part) => escapeRegExp(part))
    .join("[\\s._-]+");
  return `(?<![A-Za-z0-9])${body}(?![A-Za-z0-9])`;
}

/** Lookbehind/lookahead wrapper MoviePilot uses around group names. */
export function compileReleaseGroupRegExp(
  patterns: readonly string[] = RELEASE_GROUP_PATTERNS,
): RegExp {
  return new RegExp(`(?<=[-@\\[￡【&])(?:${patterns.join("|")})(?=$|[@.\\s\\]\\[】&])`, "i");
}

export interface CompiledStreamingPlatform {
  name: string;
  latinRe?: RegExp;
  cjkRe?: RegExp;
}

export function compileStreamingPlatforms(
  platforms: readonly StreamingPlatformSpec[] = STREAMING_PLATFORMS,
): CompiledStreamingPlatform[] {
  return platforms.map((platform) => {
    const latin = [...platform.latin].sort((a, b) => b.length - a.length);
    const cjk = [...(platform.cjk ?? [])].sort((a, b) => b.length - a.length);
    return {
      name: platform.name,
      ...(latin.length > 0 ? { latinRe: new RegExp(latin.map(latinTokenPattern).join("|"), "i") } : {}),
      ...(cjk.length > 0 ? { cjkRe: new RegExp(cjk.map(escapeRegExp).join("|")) } : {}),
    };
  });
}

